spring:
    application:
       name: DeviceMonitor
    profiles:
     active: dev

management:
  security:
    enabled: false

fugu:
    swagger:
       title: 孚谷物联网平台接口文档
       description: 孚谷物联网平台接口文档
       version: 1.0.0
       termsOfServiceUrl:
       contactName:
       contactUrl:
       contactEmail:
       license:
       licenseUrl:
